[workspace]
members = [
    # "crates/basecoin",
    "crates/config",
    "crates/helper",
    "crates/modules/auth",
    "crates/modules/bank",
    "crates/modules/gov",
    "crates/modules/ibc",
    "crates/modules/module-api",
    "crates/modules/staking",
    "crates/modules/upgrade",
    "crates/store",
]